include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/elan3257/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  ekt2k_mtk10.o

